---
- name: Spin up some EC2 instances
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Launch instances
      local_action:
        module: ec2
        aws_access_key: "{{ access }}"
        aws_secret_key: "{{ secret }}"
        region: us-east-1
        key_name: "{{ key }}"
        vpc_subnet_id: "{{ subnet }}"
        assign_public_ip: yes
        group: "{{ group }}"
        instance_type: t2.micro
        image: ami-0d4cfd66
        count: 1
        instance_tags:
          Name: "{{ name }}"
        wait: yes
      register: ec2

    - name: Add all instance public IPs to host group
      add_host: hostname={{ item.public_ip }} groups=ec2hosts
      with_items: ec2.instances
    - name: Wait for SSH
      wait_for: host={{ item.public_ip }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances